test.string: hello from springboot microservice config file
spring.datasource.platform=: Postgres
spring.datasource.url: jdbc:postgresql://localhost:5432/TaskTwo
spring.datasource.username: postgres
spring.datasource.password: ahmed
spring.datasource.initialization-mode: always
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource.data: classpath:data.sql
